name = "twittail"
type = "javascript"

account_id = ""
route = ""
workers_dev = true
zone_id = ""

kv_namespaces = [
  {binding = "Twittail_KV", id = "fb465115dff649e4acaf6fffd03c51a8"},
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
